export const ROUTE_PATHS = {
  home: '/',
  login: '/login',
  signup: '/signup',
  signupIndividual: '/signup/individual',
  signupIndividualProfile: '/signup/individual/profile',
  signupCompany: '/signup/company',
  signupCompanySetup: '/signup/company/setup',
  about: '/about',
  howToUse: '/how-to-use',
  companyGuide: '/company-guide',
  safety: '/safety',
  profile: '/profile',
  visibility: '/visibility',
  proposals: '/proposals',
  proposalDetail: '/proposals/:proposalId',
  viewHistory: '/view-history',
  companyVerify: '/company/verify',
  talents: '/talents',
  talentDetail: '/talents/:talentId',
  saved: '/saved',
  offers: '/offers',
  offerCreate: '/offers/new/:talentId',
  admin: '/admin',
  adminUsers: '/admin/users',
  adminCompanies: '/admin/companies',
  adminReports: '/admin/reports',
};

export const buildPath = {
  proposalDetail: (proposalId) => `/proposals/${proposalId}`,
  talentDetail: (talentId) => `/talents/${talentId}`,
  offerCreate: (talentId) => `/offers/new/${talentId}`,
};
